# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
# Python
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
# numpydoc
-   repo: https://github.com/Carreau/velin
    rev: 0.0.12
    hooks:
    - id: velin
      args: ["--write"]
# test if the hook in this repo is working
-   repo: ./
    rev: adb9c21f9abc24b974a172c14869b58acc3d742f
    hooks:
    -   id: dargs-check
        args: ["-f dargs._test.test_arguments"]
        files: "tests/test_arguments.json"
        additional_dependencies: []
