name: Type check
on:
  - push
  - pull_request

jobs:
  type_check:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v6
    - run: pipx run uv tool run --with .[typecheck,yaml] ty check
